//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DimBusinessPartner
    {
        public DimBusinessPartner()
        {
            this.DimProductLines = new HashSet<DimProductLine>();
        }
    
        public int id { get; set; }
         [Display(Name = "Name")]
        public string BusinessPartnerName { get; set; }
         [Display(Name = "BPCode")]
        public string BPCode { get; set; }
    
        public virtual ICollection<DimProductLine> DimProductLines { get; set; }
    }
}
