//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimBuilding
    {
        public DimBuilding()
        {
            this.DimModules = new HashSet<DimModule>();
        }
    
        public int id { get; set; }
        [Display(Name = "Building")]
        public string BuildingName { get; set; }
        [Display(Name = "Facility")]
        public Nullable<int> KeyFacility { get; set; }
    
        public virtual DimFacility DimFacility { get; set; }
        public virtual ICollection<DimModule> DimModules { get; set; }
    }
}
