//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DimCountry
    {
        public DimCountry()
        {
            this.DimFacilities = new HashSet<DimFacility>();
        }

        
        public int id { get; set; }
        [Display(Name = "Country")]
        [MustBeSelectedAttribute(ErrorMessage = "Please Select Country")]
        public string CountryName { get; set; }
        [Display(Name = "Region")]
        public Nullable<int> KeyRegion { get; set; }
    
        public virtual ICollection<DimFacility> DimFacilities { get; set; }
        public virtual DimRegion DimRegion { get; set; }
    }
}
