//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimModule
    {
        public DimModule()
        {
            this.DimFFInstances = new HashSet<DimFFInstance>();
        }

        public int id { get; set; }
        [Display(Name = "Module")]
        public string ModuleName { get; set; }
        [Display(Name = "Building")]
        public Nullable<int> KeyBuilding { get; set; }
    
        public virtual DimBuilding DimBuilding { get; set; }
        public virtual ICollection<DimFFInstance> DimFFInstances { get; set; }
    }
}
