//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MetricConfiguration
    {
        public int id { get; set; }
        [Display(Name = "Metric")]
        public Nullable<int> KeyMetricID { get; set; }
        [Display(Name = "Metric Role Type")]
        public Nullable<int> KeyMetricRoleTypeID { get; set; }
        [Display(Name = "Site")]
        public Nullable<int> KeySiteID { get; set; }
        [Display(Name = "Business Partner")]
        public Nullable<int> KeyBusinessPartnerID { get; set; }
        [Display(Name = "FF Instance")]
        public Nullable<int> KeyFFInstanceID { get; set; }
        public string Goal { get; set; }
        public string Red { get; set; }
        public string Green { get; set; }
        public string Alert { get; set; }
        [Display(Name = "Alert (MasterDataChange)")]
        public string Alert_MasterDataChange { get; set; }
        [Display(Name = "Alert (SystemErrors)")]
        public string Alert_SystemErrors { get; set; }
        [Display(Name = "Metric Manager Validation Status")]
        public string MetricManagerValidationStatus { get; set; }
        [Display(Name = "Metric Owner Validation Status")]
        public string MetricOwnerValidationStatus { get; set; }
        public string Status { get; set; }
    
        public virtual DimBusinessPartner DimBusinessPartner { get; set; }
        public virtual DimFacility DimFacility { get; set; }
        public virtual DimFFInstance DimFFInstance { get; set; }
        public virtual Metric Metric { get; set; }
        public virtual MetricRoleType MetricRoleType { get; set; }
    }
}
