//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomConfiguratorModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFCube2Entities : DbContext
    {
        public FFCube2Entities()
            : base("name=FFCube2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DimBucket> DimBuckets { get; set; }
        public DbSet<DimBuilding> DimBuildings { get; set; }
        public DbSet<DimBusinessPartner> DimBusinessPartners { get; set; }
        public DbSet<DimBusinessUnit> DimBusinessUnits { get; set; }
        public DbSet<DimCostCenter> DimCostCenters { get; set; }
        public DbSet<DimCountry> DimCountries { get; set; }
        public DbSet<DimDatetime> DimDatetimes { get; set; }
        public DbSet<DimFacility> DimFacilities { get; set; }
        public DbSet<DimFFInstance> DimFFInstances { get; set; }
        public DbSet<DimFinancialCompany> DimFinancialCompanies { get; set; }
        public DbSet<DimModule> DimModules { get; set; }
        public DbSet<DimPhysicalStation> DimPhysicalStations { get; set; }
        public DbSet<DimProcessType> DimProcessTypes { get; set; }
        public DbSet<DimProductLine> DimProductLines { get; set; }
        public DbSet<DimProductNumber> DimProductNumbers { get; set; }
        public DbSet<DimRegion> DimRegions { get; set; }
        public DbSet<DimStationType> DimStationTypes { get; set; }
        public DbSet<FactffFirstPass> FactffFirstPasses { get; set; }
        public DbSet<CISTestResultSet> CISTestResultSets { get; set; }
        public DbSet<ffPart> ffParts { get; set; }
        public DbSet<ffStation> ffStations { get; set; }
        public DbSet<ffStationType> ffStationTypes { get; set; }
        public DbSet<fsSite> fsSites { get; set; }
        public DbSet<DataPollingExecutionTime> DataPollingExecutionTimes { get; set; }
        public DbSet<FactffCompletion> FactffCompletions { get; set; }
        public DbSet<FactffDefect> FactffDefects { get; set; }
        public DbSet<RTYbyDay> RTYbyDays { get; set; }
        public DbSet<SpeedMeasure> SpeedMeasures { get; set; }
        public DbSet<Metric> Metrics { get; set; }
        public DbSet<MetricRoleType> MetricRoleTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<MetricConfiguration> MetricConfigurations { get; set; }
    }
}
